### PR TITLE
Code cleanup and Docker fixes

### LINKED ISSUE #14: Add documentation around the code.
Document planner_manager and planning_context.

              creating issue.

_Originally posted by @kamiradi in https://github.com/moveit/moveit_drake/pull/8#discussion_r1665263513_

### LINKED ISSUE #21: [Cleanup] Add relevant docstrings to plugin
add docstrings to these

_Originally posted by @sea-bass in https://github.com/moveit/moveit_drake/pull/18#discussion_r1678459172_

### PR DESCRIPTION
**Pull request by sea-bass**
I "ate the frog" 🐸  and added docstrings to the KTOpt plugin plus cleaned up the README.

Also, added a few other fixes.

* Cleaned up header files and excessive `using` directives
* Changed the string input arg in `setRobotDescription()` to be const ref
* Moved the folder containing the `generate_parameter_library` params (what was `res` anyway?)
* Fixed the `moveit_drake` folder mounting location which was broken in the last PR (#54)
* Installed `pip3` and `pre-commit` which was also accidentally removed in #54

(also, sorry I accidentally pushed this to `main` first, so I rewrote history and undid that by force-pushing to `main`)

Closes #14
Closes #21

### CODE REVIEW

File: include/ktopt_interface/ktopt_planning_context.hpp [hunk 1]
```diff
@@ -1,103 +1,119 @@
...
+   * @brief Adds path position constraints, if any, to the planning problem.
+   * @param trajopt The Drake mathematical program containing the trajectory optimization problem.
+   * @param plant The Drake multibody plant to use for planning.
+   * @param plant_context The context associated with the multibody plant.
+   * @param padding Additional position padding on the MoveIt constraint, in meters.
+   * This ensures that constraints are more likely to hold for the entire trajectory, since the
+   * Drake mathematical program only optimizes constraints at discrete points along the path.
+   */
   void addPathPositionConstraints(KinematicTrajectoryOptimization& trajopt, const MultibodyPlant<double>& plant,
                                   Context<double>& plant_context, const double padding);
```
Comment (sea-bass) [inline include/ktopt_interface/ktopt_planning_context.hpp:92]: @kamiradi Ensure you add a similar thing to your standing PR once this goes in!

**Review by kamiradi — APPROVED** [review]
LGTM, thanks for this @sea-bass.
